version: "3"

services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: ./apps/webapp/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - ./apps/webapp/.env
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 8001:80
    networks:
      - app_network
    env_file:
      - ./apps/backend/.env
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true